name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "ci-cd" ]
  pull_request:
    branches: [ "main", "ci-cd" ]
  workflow_dispatch:

jobs:
  test:
    name: CI - Build, Test, and Quality Scan
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run tests and SonarCloud
        run: ./gradlew check jacocoTestReport sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} --info